import pandas as pd
df=pd.read_csv('zomato.csv')
df.info()
df.drop('rest_type',axis=1,inplace=True)
df.drop('menu_item',axis=1,inplace=True)
df.drop('phone',axis=1,inplace=True)
df.drop('address',axis=1,inplace=True)
df.drop('url',axis=1,inplace=True)
df.drop('dish_liked',axis=1,inplace=True)
df.drop('reviews_list',axis=1,inplace=True)
df.drop('reviews_list',axis=1,inplace=True)
df.info()
df.drop_duplicates(inplace=True)
df.rename(columns={"name":"restaurant_name","rate":"rating","listed_in(type)":"restaurant_type"},inplace=True)
df.rename(columns={"approx_cost(for two people)":"cost_per_person"},inplace=True)
df.info()
df['rating']=df['rating'].astype(str)
df['rating']=df['rating'].str.replace('/5','')
df['rating']=df['rating'].str.replace('NEW','nan')
df['rating']=df['rating'].str.replace('-','nan')
df['rating']=df['rating'].astype(float)
df=df.dropna(subset=(['cuisines','location','approx_cost(for two people)']))
df.info()
df['rating']=df['rating'].fillna(df['rating'].mean())
df.info()
df['cost_per_person']=df['cost_per_person'].astype(str)
df['cost_per_person'] = df['cost_per_person'].str.replace(',', '')
df['cost_per_person']=df['cost_per_person'].astype(int)
df['cost_per_person'] = df['cost_per_person'] / 2
df.info()
df['restaurant_name']=df['restaurant_name'].astype("string")
df['online_order']=df['online_order'].astype("string")
df['book_table']=df['book_table'].astype("string")
df['location']=df['location'].astype("string")
df['cuisines']=df['cuisines'].astype("string")
df['restaurant_type']=df['restaurant_type'].astype("string")
df['City']=df['City'].astype("string")
df.info()
df.rename(columns={"listed_in(city)":"City"},inplace=True)
df.drop('City',axis=1,inplace=True)
df.info()
df.to_csv('zomato_clean_data.csv', index=False)